const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],copy=x=>JSON.parse(JSON.stringify(x));
const patterns={focus:{name:'Focus & reflect',why:'One clear choice followed by generous reflection space.',blocks:[['Today’s focus','choices',28,104,760,160],['What supports it','checklist',28,278,373,300],['What may get in the way','lines',415,278,373,300],['Notes for later','lines',28,592,760,438]]},weekly:{name:'Weekly overview',why:'Balances priorities, appointments, and space to notice progress.',blocks:[['Three priorities','checklist',28,104,373,230],['Appointments','lines',415,104,373,230],['Monday – Wednesday','lines',28,348,373,420],['Thursday – Sunday','lines',415,348,373,420],['Weekly reflection','lines',28,782,760,248]]},tracker:{name:'Gentle tracker',why:'Makes patterns visible without turning the page into a scorecard.',blocks:[['What I’m noticing','choices',28,104,760,150],['Daily check-in','checklist',28,268,373,430],['Helpful conditions','lines',415,268,373,430],['One adjustment to try','lines',28,712,760,318]]},review:{name:'Review & next step',why:'Closes the loop with evidence, learning, and one realistic next action.',blocks:[['What worked','lines',28,104,373,330],['What felt difficult','lines',415,104,373,330],['What I learned','lines',28,448,760,260],['My next gentle step','lines',28,722,760,308]]}};
const library=[['Welcome & intention','Set a useful tone and name what this planner supports.','focus'],['What matters now','Clarify the customer’s current priorities.','focus'],['Weekly direction','Turn priorities into a workable week.','weekly'],['Daily check-in','Notice energy, needs, and progress.','tracker'],['Support plan','Identify helpful conditions and resources.','focus'],['Review & continue','Reflect and choose the next realistic step.','review'],['Progress tracker','See patterns across several days.','tracker'],['Notes & ideas','Capture thoughts without sorting them immediately.','focus'],['Monthly overview','Connect dates, priorities, and milestones.','weekly'],['Closing reflection','Recognize learning and plan what comes next.','review']];
const colors=['sage','lav','blue','warm'],themes=['#b2c6b1','#c6b5c8','#7b9fb3','#e6d7d3'];let project,pageIndex=0,blockIndex=null,zoom=.58,past=[],future=[],timer;
function block(row,i){let[t,type,x,y,w,h]=row,c=type==='checklist'?{type,items:['A helpful action','Another small step'],blank_rows:5}:type==='choices'?{type,control:'radio',options:['Ready','Unsure','Not today'],lines_after:3}:{type,rows:Math.max(4,Math.floor((h-60)/22)),prompt:''};return{x,y,w,h,title:t,color:colors[i%4],content:c}}
function page([label,subtitle,pattern],i){return{label,title:label.toUpperCase(),subtitle,theme:themes[i%4],concept:subtitle,pattern,notes:'',blocks:patterns[pattern].blocks.map(block)}}
function fresh(){return{set_title:'Fresh Start Planner',footer_label:'Your Brand | Fresh Start Planner',audience:'Busy adults rebuilding a steady weekly routine',outcome:'Notice what matters, choose realistic priorities, and review progress without pressure.',tone:'calm',pages:library.slice(0,6).map(page)}}
function load(){try{project=JSON.parse(localStorage.getItem('plannerStudio'))||fresh()}catch{project=fresh()}$('#title').value=project.set_title;$('#audience').value=project.audience;$('#outcome').value=project.outcome;$('#count').value=project.pages.length;render()}
function before(){past.push(copy(project));if(past.length>50)past.shift();future=[];$('#saved').textContent='Saving…'}
function change(fn,msg){before();fn();render();clearTimeout(timer);timer=setTimeout(()=>save(msg),250)}
function save(msg){localStorage.setItem('plannerStudio',JSON.stringify(project));$('#saved').textContent='Saved locally';$('#undo').disabled=!past.length;$('#redo').disabled=!future.length;if(msg)toast(msg)}
function undo(){if(!past.length)return;future.push(copy(project));project=past.pop();pageIndex=Math.min(pageIndex,project.pages.length-1);blockIndex=null;render();save('Change undone')}
function redo(){if(!future.length)return;past.push(copy(project));project=future.pop();render();save('Change restored')}
function view(id){$$('.flow,.editor').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));if(id==='editor')setTimeout(fit,20);if(id==='review')review()}
function createBlueprint(){project.set_title=$('#title').value.trim();project.audience=$('#audience').value.trim();project.outcome=$('#outcome').value.trim();project.tone=$('input[name=tone]:checked').value;project.footer_label='Your Brand | '+project.set_title;project.pages=library.slice(0,+$('#count').value).map(page);pageIndex=0;blockIndex=null;save('Blueprint created');render();view('blueprint')}
function render(){project.pages ||= [];$('#projectName').textContent=project.set_title;renderBlueprint();renderRail();renderPage();renderInspector();renderPatterns();$('#undo').disabled=!past.length;$('#redo').disabled=!future.length}
function renderBlueprint(){$('#reason').textContent=`Recommended for ${project.audience}: it begins with clarity, builds a repeatable practice, and ends with reflection.`;$('#blueprintList').innerHTML=project.pages.map((p,i)=>`<li class="blueprint-item" draggable="true" data-i="${i}"><span class="handle">⠿</span><div><strong>${i+1}. ${esc(p.label)}</strong><p>${esc(p.subtitle)}</p></div><span><button class="up" ${i?'':'disabled'} aria-label="Move earlier">↑</button><button class="down" ${i<project.pages.length-1?'':'disabled'} aria-label="Move later">↓</button><button class="remove" aria-label="Remove page">×</button></span></li>`).join('');$$('.up').forEach((b,i)=>b.onclick=()=>movePage(i,-1));$$('.down').forEach((b,i)=>b.onclick=()=>movePage(i,1));$$('.remove').forEach((b,i)=>b.onclick=()=>project.pages.length===1?toast('A planner needs at least one page'):change(()=>project.pages.splice(i,1),'Page removed'));let from;$$('.blueprint-item').forEach(x=>{x.ondragstart=()=>from=+x.dataset.i;x.ondragover=e=>e.preventDefault();x.ondrop=()=>{let to=+x.dataset.i;if(to!==from)change(()=>{let[p]=project.pages.splice(from,1);project.pages.splice(to,0,p)},'Page reordered')}})}
function movePage(i,d){change(()=>{let[p]=project.pages.splice(i,1);project.pages.splice(i+d,0,p)},'Page reordered')}
function addPage(){let i=project.pages.length;change(()=>project.pages.push(page(library[i%library.length],i)),'Page added')}
function renderRail(){$('#pageList').innerHTML=project.pages.map((p,i)=>`<li><button class="thumb ${i===pageIndex?'active':''}" data-i="${i}" style="--theme:${p.theme}" ${i===pageIndex?'aria-current="page"':''}><span class="mini"></span><span>${i+1}. ${esc(p.label)}</span></button></li>`).join('');$$('.thumb').forEach(x=>x.onclick=()=>{pageIndex=+x.dataset.i;blockIndex=null;render()})}
function renderPage(){let p=project.pages[pageIndex];if(!p)return;$('#page').style.cssText=`--theme:${p.theme};--zoom:${zoom}`;$('#stage').style.width=816*zoom+'px';$('#stage').style.height=1056*zoom+'px';$('#zoom').textContent=Math.round(zoom*100)+'%';$('#page').innerHTML=`<div class="page-head"><div class="page-title">${esc(p.title)}</div><div class="page-subtitle">${esc(p.subtitle)}</div></div>${p.blocks.map(renderBlock).join('')}<div class="page-foot"><span>${esc(project.footer_label)}</span><span>${pageIndex+1} of ${project.pages.length}</span></div>`;$$('.block').forEach(bindBlock)}
function renderBlock(b,i){let body='';if(b.content.type==='checklist')body=[...(b.content.items||[]),...Array(b.content.blank_rows||0).fill('')].map(x=>`<div class="checkrow"><i class="box"></i>${esc(x)}</div>`).join('');else if(b.content.type==='choices')body=`<b>${esc(b.content.prompt||'Choose what fits today')}</b><div class="checkrow">${(b.content.options||[]).map(x=>'○ '+esc(x)).join(' &nbsp; ')}</div>`+lines(b.content.lines_after||3);else body=(b.content.prompt?`<b>${esc(b.content.prompt)}</b>`:'')+lines(Math.min(18,b.content.rows||6));return`<section class="block ${i===blockIndex?'selected':''}" tabindex="0" data-i="${i}" style="left:${b.x}px;top:${b.y}px;width:${b.w}px;height:${b.h}px"><div class="block-head ${b.color}">${esc(b.title)}</div><div class="block-body">${body}</div>${i===blockIndex?'<button class="resize" type="button" aria-label="Resize section" title="Drag to resize"></button>':''}</section>`}
function lines(n){return Array(n).fill('<div class="line"></div>').join('')}
function bindBlock(el){let i=+el.dataset.i;el.onclick=e=>{e.stopPropagation();if(blockIndex!==i){blockIndex=i;renderPage();renderInspector()}};el.onkeydown=e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();let n=e.shiftKey?14:7,dx=e.key==='ArrowLeft'?-n:e.key==='ArrowRight'?n:0,dy=e.key==='ArrowUp'?-n:e.key==='ArrowDown'?n:0;moveBlock(i,dx,dy)};let handle=el.querySelector('.resize');if(handle)handle.onpointerdown=e=>{e.stopPropagation();e.preventDefault();let b=project.pages[pageIndex].blocks[i],sx=e.clientX,sy=e.clientY,ow=b.w,oh=b.h;before();handle.setPointerCapture(e.pointerId);handle.onpointermove=v=>{b.w=snap(Math.max(180,Math.min(788-b.x,ow+(v.clientX-sx)/zoom)));b.h=snap(Math.max(92,Math.min(1030-b.y,oh+(v.clientY-sy)/zoom)));el.style.width=b.w+'px';el.style.height=b.h+'px'};handle.onpointerup=()=>{handle.onpointermove=null;renderPage();renderInspector();save('Section resized')}};el.onpointerdown=e=>{if(e.button||e.target.closest('.resize'))return;e.preventDefault();blockIndex=i;let b=project.pages[pageIndex].blocks[i],sx=e.clientX,sy=e.clientY,ox=b.x,oy=b.y;before();el.setPointerCapture(e.pointerId);el.onpointermove=v=>{b.x=snap(Math.max(28,Math.min(788-b.w,ox+(v.clientX-sx)/zoom)));b.y=snap(Math.max(104,Math.min(1030-b.h,oy+(v.clientY-sy)/zoom)));el.style.left=b.x+'px';el.style.top=b.y+'px'};el.onpointerup=()=>{el.onpointermove=null;renderPage();renderInspector();save('Section moved')}}}
function moveBlock(i,dx,dy){let b=project.pages[pageIndex].blocks[i];change(()=>{b.x=snap(Math.max(28,Math.min(788-b.w,b.x+dx)));b.y=snap(Math.max(104,Math.min(1030-b.h,b.y+dy)))},'Section moved')}function snap(n){return Math.round(n/7)*7}
function field(id,value,set,area=false){return`<label>${id}<${area?'textarea rows="3"':'input'} data-field="${id}" ${area?'':`value="${attr(value)}"`}>${area?esc(value):''}${area?'</textarea>':'>'}</label>`}
function renderInspector(){let p=project.pages[pageIndex];if(!p)return;$('#theme').value=p.theme;$('#notes').value=p.notes||'';if(blockIndex===null){$('#selection').textContent='Page details';$('#content').innerHTML=field('Page name',p.label)+field('Printed title',p.title)+field('Subtitle',p.subtitle,null,true);$('#layout').textContent='Select a section to edit its position.';$('#blockColor').disabled=true;bindFields([v=>p.label=v,v=>p.title=v,v=>p.subtitle=v])}else{let b=p.blocks[blockIndex];$('#selection').textContent=b.title;$('#blockColor').disabled=false;$('#blockColor').value=b.color;$('#content').innerHTML=field('Section title',b.title)+field('Prompt',b.content.prompt||'',null,true)+`<label>Response style<select id="type"><option value="lines">Writing lines</option><option value="checklist">Checklist</option><option value="choices">Choices</option></select></label><button id="delete">Delete section</button>`;$('#type').value=b.content.type;$('#layout').innerHTML=`<div class="row">${['x','y','w','h'].map(k=>`<label>${({x:'Left',y:'Top',w:'Width',h:'Height'})[k]}<input type="number" data-geo="${k}" value="${b[k]}"></label>`).join('')}</div>`;bindFields([v=>b.title=v,v=>b.content.prompt=v]);$('#type').onchange=e=>change(()=>b.content={type:e.target.value,rows:8,items:['First item','Second item'],blank_rows:5,options:['Yes','Maybe','Not today'],lines_after:3},'Response style changed');$('#delete').onclick=()=>change(()=>{p.blocks.splice(blockIndex,1);blockIndex=null},'Section deleted');$$('[data-geo]').forEach(x=>x.onchange=e=>change(()=>b[e.target.dataset.geo]=+e.target.value,'Layout updated'))}}
function bindFields(setters){$$('[data-field]').forEach((x,i)=>x.onchange=e=>change(()=>setters[i](e.target.value),'Text updated'))}
function renderPatterns(){$('#patternGrid').innerHTML=Object.entries(patterns).map(([id,p])=>`<button type="button" class="pattern" data-pattern="${id}"><strong>${p.name}</strong><small>${p.why}</small></button>`).join('');$$('.pattern').forEach(x=>x.onclick=()=>{let id=x.dataset.pattern;change(()=>{let p=project.pages[pageIndex];p.pattern=id;p.blocks=patterns[id].blocks.map(block);blockIndex=null},'Page pattern changed');$('#dialog').close()})}
function fit(){let r=$('#scroll').getBoundingClientRect();zoom=Math.max(.28,Math.min(.78,(r.height-44)/1056,(r.width-44)/816));renderPage()}
async function validate(){try{return await(await fetch('/api/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(project)})).json()}catch{return{valid:false,findings:['Planner Studio could not reach the local generator. Restart it and try again.']}}}
async function review(){$('#reviewGrid').innerHTML=project.pages.map((p,i)=>`<div class="reviewcard"><div class="reviewpage" style="--theme:${p.theme}"></div><strong>${i+1}. ${esc(p.label)}</strong><small>${patterns[p.pattern]?.name||'Custom layout'}</small></div>`).join('');$('#findings').innerHTML='<p>Checking every page…</p>';let r=await validate();$('#score').textContent=r.valid?'Ready':'Needs review';$('#score').style.background=r.valid?'var(--sage2)':'var(--blush)';$('#findings').innerHTML=r.findings.length?r.findings.map(x=>`<div class="finding ${x.startsWith('ERROR')?'bad':''}">${esc(x)}</div>`).join(''):'<div class="finding good">All pages passed the publication check.</div>';$('#html').disabled=!r.valid}
async function exportHtml(){let r=await fetch('/api/render',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(project)});if(!r.ok)return toast('Fix the listed issues before exporting');download(await r.blob(),slug(project.set_title)+'.html')}function exportJson(){download(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),slug(project.set_title)+'.json')}function download(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast(name+' downloaded')}function slug(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'planner'}function toast(s){let t=$('#toast');t.textContent=s;t.classList.add('show');clearTimeout(t.t);t.t=setTimeout(()=>t.classList.remove('show'),2200);$('#live').textContent=s}function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}const attr=esc;
$$('[data-view]').forEach(x=>x.onclick=()=>view(x.dataset.view));$('#briefForm').onsubmit=e=>{e.preventDefault();createBlueprint()};$('#addPage').onclick=$('#addPage2').onclick=addPage;$('#undo').onclick=undo;$('#redo').onclick=redo;$('#fit').onclick=fit;$('#minus').onclick=()=>{zoom=Math.max(.25,zoom-.05);renderPage()};$('#plus').onclick=()=>{zoom=Math.min(.9,zoom+.05);renderPage()};$('#patterns').onclick=()=>$('#dialog').showModal();$('#check').onclick=async()=>{let r=await validate();toast(r.valid?'This planner passes every check':r.findings.length+' items need review')};$('#theme').onchange=e=>change(()=>project.pages[pageIndex].theme=e.target.value,'Page color changed');$('#blockColor').onchange=e=>blockIndex!==null&&change(()=>project.pages[pageIndex].blocks[blockIndex].color=e.target.value,'Section color changed');$('#notes').onchange=e=>change(()=>project.pages[pageIndex].notes=e.target.value,'Notes saved');$('#page').onclick=()=>{blockIndex=null;renderPage();renderInspector()};$('#html').onclick=exportHtml;$('#json').onclick=exportJson;window.onresize=()=>$('#editor').classList.contains('active')&&fit();load();
